name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Google Cloud authentication
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    # Step 3: Configure Google Cloud Project
    - name: Set up Google Cloud Project
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}

    # Step 4: Build and push Docker image to Google Container Registry
    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/blazor-app

    # Step 5: Deploy to Google Cloud Run
    - name: Deplo app to Cloud Run
      run: |
        gcloud run deploy blazor-app \
          --image gcr.io/${{ secrets.GCP_PROJECT }}/blazor-app \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated